[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[dev]
  publish = "dist"
